#!/usr/bin/env python
"""
export_glossary.py

Generate docs/trustmark-glossary.md from the source Excel glossary.

- Reads the Excel file defined in SOURCE_XLSX.
- Drops the "Source Document" column (case-insensitive).
- Writes a Markdown page with the glossary controls + table.
- Converts Excel newlines into real <br> (NOT &lt;br&gt;).

Run:
    python export_glossary.py
"""

from pathlib import Path
import html
import pandas as pd

# ---------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------

# Path to the source Excel file (relative to the repo root)
SOURCE_XLSX = Path("data/TrustMark_Glossary raw file.xlsx")

# Path to the Markdown file MkDocs serves
OUTPUT_MD = Path("docs/trustmark-glossary.md")


# ---------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------

def load_glossary_dataframe(path: Path) -> pd.DataFrame:
    """Load the glossary from Excel and drop the Source Document column."""
    if not path.exists():
        raise FileNotFoundError(f"Source Excel file not found: {path.resolve()}")

    df = pd.read_excel(path)

    # Drop "Source Document" column (case-insensitive match).
    cols_lower = {c.lower().strip(): c for c in df.columns}
    for target in ("source document", "source_document", "sourcedocument"):
        if target in cols_lower:
            df = df.drop(columns=[cols_lower[target]])
            break

    return df


def fmt_cell(value) -> str:
    """
    Make a safe Markdown cell.

    - Keeps line breaks as <br>
    - Escapes everything else so pipes/HTML don't break the table
    """
    if pd.isna(value):
        return ""

    text = str(value).replace("\r\n", "\n")

    # Put placeholders in for line breaks first
    text = text.replace("\n", "__TM_BR__")

    # Escape everything
    text = html.escape(text, quote=True)

    # Restore real HTML line breaks
    text = text.replace("__TM_BR__", "<br>")

    return text


def dataframe_to_markdown_table(df: pd.DataFrame) -> str:
    """Convert dataframe into a Markdown table."""
    cols = list(df.columns)

    header = "| " + " | ".join(cols) + " |"
    separator = "| " + " | ".join(["---"] * len(cols)) + " |"

    rows = []
    for _, row in df.iterrows():
        cells = [fmt_cell(row[col]) for col in cols]
        rows.append("| " + " | ".join(cells) + " |")

    return "\n".join([header, separator] + rows)


def build_page_markdown(table_md: str) -> str:
    """Wrap the glossary table with fixed page structure."""
    header_block = """<!-- This file is auto-generated by export_glossary.py.
Do not manually edit the glossary table — changes will be overwritten. -->

<!-- Glossary controls -->
<div class="glossary-controls">
  <button class="tm-btn" data-type="all">All</button>
  <button class="tm-btn" data-type="term">Term</button>
  <button class="tm-btn" data-type="acronym">Acronym</button>
  <button class="tm-btn" data-type="metric">Metric</button>

  <span class="domain-filter-wrap">
    <select id="domain-filter">
      <option value="">All domains</option>
    </select>
  </span>

  <input id="glossary-search" type="text" placeholder="Search all columns…" />
</div>

<div class="glossary-contact">
For any edits or additions to this TrustMark Glossary, please contact
<a href="mailto:phitchen@trustmark.org.uk">Pete Hitchen</a>.
</div>

# TrustMark Glossary

"""
    return header_block + table_md + "\n"


def main() -> None:
    print(f"Loading glossary from: {SOURCE_XLSX}")
    df = load_glossary_dataframe(SOURCE_XLSX)

    print(f"Loaded {len(df)} rows and {len(df.columns)} columns after dropping Source Document (if present).")

    table_md = dataframe_to_markdown_table(df)
    page_md = build_page_markdown(table_md)

    OUTPUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_MD.write_text(page_md, encoding="utf-8")

    print(f"Wrote glossary page to: {OUTPUT_MD.resolve()}")


if __name__ == "__main__":
    main()
